// More fictional sample stories for the browser-only demo.
// [category, title, summary, body (markdown), views, featured, daysAgo]
export const MORE_ARTICLES = [
  ['World', 'Ferry service to the northern islands resumes after winter break',
    'Daily crossings restart this week with a newer vessel and a cheaper fare for islanders.',
    'The Kestrel Sound ferry will sail twice a day from Monday, ending a four-month gap in which residents relied on a weekly supply boat.\n\n## What changes\n\nThe new vessel carries 140 passengers and twelve cars, and its quieter engines were a condition of the harbour licence. Island residents pay a flat fare, while visitors pay the standard rate.\n\n> "Our shop shelves were bare by February," said Priya Anand, who runs the general store on Little Skerry.\n\nThe timetable will be reviewed after the summer season.',
    980, false, 4],
  ['World', 'Neighbouring towns open a shared border market',
    'Traders from both sides of the river can now sell under one roof, with a single set of rules.',
    'A covered market straddling the Alder River opened on Saturday, the first project completed under the new cross-border cooperation agreement.\n\n## How it works\n\n- Stalls are allocated by lottery twice a year\n- Prices are shown in both currencies\n- Food safety checks follow whichever rule is stricter\n\nOrganisers expect around 3,000 visitors each weekend. A second phase will add a small museum about the river trade.',
    1130, false, 6],
  ['Technology', 'Open-source maps project reaches one million contributors',
    'Volunteers have traced roads, footpaths and flood channels in regions that commercial maps ignore.',
    'A community mapping project announced that it has passed one million registered contributors, many of them students who map their own neighbourhoods after school.\n\n## Why it matters\n\nAid groups used the data last year to plan routes after heavy rain, and several city governments now publish their street lists in the same format.\n\n**Quality checks** are done by other volunteers, who review each edit within a few days.',
    1520, true, 5],
  ['Technology', 'A small team ports a classic text adventure to the browser',
    'The remake keeps the original puzzles but adds screen reader support and saved games.',
    'Three developers spent eighteen months rebuilding a 1980s text adventure so that it runs in any modern browser, with no download and no account.\n\n## Accessibility first\n\nEvery room description is announced by screen readers, and players can change font size, spacing and colours. Progress is saved on the device.\n\nThe team says the hardest part was preserving the quirky humour of the original parser while making its error messages friendlier.',
    870, false, 9],
  ['Technology', 'Why your phone suggests the same three apps every morning',
    'A short explainer on how on-device prediction works, and how to turn it off.',
    'Most phones now learn which app you open at which time of day and move it to the front of the home screen.\n\n## How it works\n\nThe prediction runs on the device itself. It looks at the time, your location category (home, work, travelling) and the last few apps you used.\n\n## Turning it off\n\n1. Open settings and find the home screen section\n2. Switch off suggestions\n3. Clear the usage history if you want to start fresh',
    2040, false, 11],
  ['Business', 'Regional bank launches fee-free accounts for under-25s',
    'The accounts come with no monthly charge and a free overdraft buffer of 100.',
    'A regional bank has introduced a current account for customers aged 18 to 24 with no monthly charges and a small buffer that never incurs fees.\n\n## What is included\n\n- A contactless card and mobile app\n- Free transfers within the country\n- Spending summaries by category\n\nAnalysts say the move is aimed at keeping students from switching to online-only rivals. The offer is open until the end of the year.',
    760, false, 7],
  ['Business', 'Town centre vacancies fall for the third quarter in a row',
    'Pop-up shops, craft studios and a new food hall have filled a quarter of the empty units.',
    'The share of empty shop units in the town centre dropped to 9 percent, the lowest figure in six years, according to the latest business improvement district count.\n\n## What filled the gaps\n\nTemporary leases with low rent have let makers and small food businesses test an idea before committing to a long contract. Several of the pop-ups have since signed permanent leases.\n\nThe council plans to extend the scheme to two neighbouring streets.',
    1090, false, 12],
  ['Business', 'Farmers share a cold store to cut food waste',
    'Seven growers pooled funds for a refrigerated warehouse that keeps berries fresh for an extra week.',
    'A cooperative of seven fruit growers has opened a shared cold store beside the main road to the market town.\n\n## The numbers\n\nBefore the store, roughly one tray in eight was thrown away unsold. In the first month the figure fell to one in twenty.\n\n> "We used to pick at dawn and panic by noon," said grower Tomas Reyes. "Now we have time to plan."\n\nThe cooperative rents spare space to local bakeries and caterers.',
    640, false, 14],
  ['Science', 'Volunteers log record numbers of pollinators in a city-wide count',
    'Bees, hoverflies and moths were spotted in parks, balconies and even rooftops.',
    'More than 4,000 residents took part in this year\'s pollinator count, photographing insects on flowers during a single weekend.\n\n## Highlights\n\nScientists confirmed 112 species, including a solitary bee not seen in the region for decades. Gardens with unmown corners had twice as many visitors as tidy lawns.\n\nThe data will help the council choose where to plant wildflower strips next spring.',
    1380, true, 8],
  ['Science', 'New study links evening light to how children sleep',
    'Dimming screens and lamps an hour before bed shortened the time it took to fall asleep.',
    'A school-based study of 600 children found that those who followed a simple evening routine fell asleep about fifteen minutes faster.\n\n## The routine\n\n1. Dim lights an hour before bedtime\n2. Switch screens to a warmer setting\n3. Keep the bedroom cool and quiet\n\nResearchers caution that sleep also depends on age and daily activity, and they plan a larger trial next year.',
    1710, false, 10],
  ['Sports', 'Wheelchair basketball club celebrates a decade of open sessions',
    'The weekly drop-in nights have introduced hundreds of newcomers to the sport.',
    'Harbour Hawks, a wheelchair basketball club, marked ten years of free open sessions with a tournament that drew teams from five towns.\n\nPlayers of every ability are welcome, and chairs are lent out for the evening. Coach Dana Whitfield said the aim has always been simple: "Come once, and see if you like it."\n\nThe club is now raising money for a second court.',
    520, false, 13],
  ['Sports', 'Teenage climber sets a new national record on the indoor wall',
    'At sixteen, Mei Tanaka finished the speed route in under seven seconds.',
    'Mei Tanaka set a national speed-climbing record at the regional championships, finishing the fifteen-metre wall in 6.9 seconds.\n\n## Training\n\nShe trains five evenings a week and credits her coach for focusing on technique rather than strength. "Every foot placement counts," she said.\n\nTanaka will compete in the national finals next month.',
    1450, false, 15],
  ['Culture', 'Street food festival brings twenty-six kitchens to the old docks',
    'Dishes from eleven regions, plus a late-night cinema screening on the quayside.',
    'The old docks will host a weekend food festival with twenty-six kitchens, from dumpling carts to family-run bakeries.\n\n## What to expect\n\n- Tasting plates under five euros\n- A cooking demo stage with local chefs\n- Live music on both evenings\n\nEntry is free, and all stalls must use compostable packaging.',
    1230, false, 16],
  ['Culture', 'Community choir records its first album in a converted chapel',
    'Sixty singers aged nine to eighty-four share one microphone setup and a lot of tea.',
    'The Millbrook Community Choir has released its first album, recorded over three weekends in a deconsecrated chapel with remarkable acoustics.\n\n## The sound\n\nThe set mixes folk songs, a few hymns and one new piece written by a member who works as a bus driver.\n\nProceeds will fund a bursary for young singers.',
    690, false, 18],
  ['World', 'Cycling highway links three cities without a single traffic light',
    'The 42 km route opened on Sunday, with rest stops, repair stations and night lighting.',
    'A new protected cycling highway now connects the three largest cities in the valley, running along the old canal towpath and a former rail line.\n\n## Details\n\nThe route is lit after dark, has air pumps every 5 km and crosses roads by bridges and underpasses.\n\nPlanners expect commuters to replace around 6,000 car trips a day.',
    1890, true, 20],
  ['Technology', 'Free coding evenings for retirees fill up within a day',
    'The library programme pairs volunteers with first-time programmers for relaxed two-hour sessions.',
    'Spaces in the library\'s new "Code at Any Age" evenings disappeared within a day of being announced.\n\n## What learners build\n\nMost start with a personal web page or a small spreadsheet automation. One group is building a database of local oral history recordings.\n\nVolunteers say the questions are the best part: "People ask why, not just how."',
    820, false, 22],
];
